### Test Register - success


POST http://localhost:4000/api/register
Content-Type: application/json

{
  "email": "darmawandoni6@gmail.com",
  "password": "kiasu123"
}

POST http://localhost:4000/api/login
Content-Type: application/json
{
  "email": "darmawandoni6@gmail.com",
  "password": "kiasu123"
}

